### ISSUE TITLE
react page not working properly

### ISSUE THREAD

**Issue by saisathwikmarka1** [prnvbaraiya/E-Voting-System-Using-Blockchain#1]
its not responding properly ,pages are not opening
![Screenshot (3)](https://user-images.githubusercontent.com/104423130/223682218-55cdf9e5-afbe-4ad1-8744-1f7f7d2146db.png)

**Comment by prnvbaraiya** [comment]
Give me a console error if any

I tried running the code again in my system and everything works fine I don't get any issues to make sure to use the below info

=>For admin
visit: http://localhost:3000/admin 
email: admin@gmail.com 
pass: admin123

=>File Changes
-Make sure you have the correct details in .env file
-In Face, Folder Make Sure to add Your Photo 
-In encode.py
Enter Face folder path value on line 6
-In authcontroller.js
Update line 284

I hope it helps if not feel free to contact me at my mail id baraiyaprnv@gmail.com

**Comment by saisathwikmarka1** [comment]
Bro in react page the page elements are not displaying just the header section got displayed Sent from my iPhoneOn 08-Mar-2023, at 3:30 PM, Pranav Baraiya ***@***.***> wrote:﻿
What's not working?

**Comment by prnvbaraiya** [comment]
There is only one image, and the navbar and footer have also changed to home.jsx with less code. you can design home page as you need I haven't focused more on designing pages. I have used material from UI; you can refer to their documentation for adding any more components.
