### ISSUE TITLE
Readme.md missing Database name

### ISSUE THREAD

**Issue by KishorJena** [prnvbaraiya/E-Voting-System-Using-Blockchain#2]
There is instruction about collections and following that we can get the schema as well but what should be the database name?

**Comment by prnvbaraiya** [comment]
The choice of database name is up to you. You can pick any name for your database, but be sure to use the correct name in the `MONGO_URL` field in your `.env` file.

For example, if your database name is **VotingSystem**, your URL should be formatted like this:
`MONGO_URL = mongodb+srv://userName:Password@some.clouster.mongodb.net/VotingSystem`
